from classes.customer import Customer
import pytest

"""
This test will utilize monkeypatch to mimick user input. The goal of this test
is to ensure a customer dictionary can be created and generated by a user.

ENSURE TO UTILIZE TEST DRIVEN DEVELOPMENT
"""


def test_05_create_customer_dict(monkeypatch):
    choices = [
        "Monica",
        'y',
        "Gellar",
        'Y',
        "aoiuedhfaweorfihaf",
        "sx",
    ]
    expected_result = {"id":1, "first_name":"Monica","last_name":"Gellar","account_type":"sx"}
    input_val = iter(choices)
    monkeypatch.setattr("builtins.input", lambda _: next(input_val))
    assert Customer.create_a_customer_dict() == expected_result


    
