name: GitHub Classroom Workflow

on:
  push:
    branches: [main, master]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      run: |
        sudo apt install python3
        sudo apt-get install python3-pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Autograder
      uses: education/autograding@v1
      continue-on-error: true
 